### PR TITLE
Update langtags_schema.json

### PR DESCRIPTION
**Pull request by darcywong00**
Follow-on to https://github.com/silnrsi/langtags/commit/725097caf94ef347aaab2eb15644babddc34ea3b

Theses are the changes I had to make to langtags_schema.json in order to validate the master branch of langtags.json

### CODE REVIEW

**Comment by darcywong00** [comment]
@mhosken - if you get a chance, can you review?

**Comment by DavidLRowe** [comment]
Thanks @darcywong00 !

**Comment by DavidLRowe** [comment]
@mhosken IIUC this change won't get to production until we push to the release branch.

**Comment by DavidLRowe** [comment]
The updated files on master branch were pushed to release last week, so this change should be visible now.

**Pull request merged**
