### PR TITLE
Remove erroneous Ancient Greek variations

### PR DESCRIPTION
**Pull request by conradarcturus**
Ancient Greek was only written in the Greek alphabet. This change removes the variations on Ancient Greek -- fixing the likely subtags for it. Let me know if you need me to follow up with other changes.

1. Mycenaean Greek (gmy) was written in Linear B (Linb)
2. Eteocypriot (ecy) was written in the Cypriot Syllabary (Cprt) – it is not related to Greek in any way, not even indo-european.
3. Ancient Greek (grc) is the only language of these written in the Greek alphabet (Grek). 

See more context from the CLDR ticket https://unicode-org.atlassian.net/browse/CLDR-11570

### CODE REVIEW

**Comment by srl295** [comment]
Error probably came in from CLDR originally.

**Comment by DavidLRowe** [comment]
Thanks for your PR, Conrad. Feel free to raise an issue or submit a PR when you find things that should be corrected.

Yes, CLDR is one of the sources where we pick up information for langtags. I'll let @LornaSIL decide whether to make these changes to langtags.csv now or wait until they come in from CLDR.

Note that making changes to langtags.json and langtags.txt is not needed as they are rebuilt whenever changes are made to source files (of which langtags.csv is one).

**Comment by LornaSIL** [comment]
Thanks Conrad! I'd like to at least know if this comes with CLDR endorsement before we make the changes.

**Comment by LornaSIL** [comment]
Since I see from the CLDR ticket that this has been processed there, I've dealt with this in langtags.csv. I'm not sure when we plan to do a release of `langtags.json`. Thanks so much.

**Comment by srl295** [comment]
Looks like the work was in https://github.com/silnrsi/langtags/commit/b72da80b27cc2f882bb08a332d1c91c53bae9ce2 (for the record)

**Comment by conradarcturus** [comment]
Thanks so much for quickly pivoting on the changes!

Although, I realize that may have acted too quickly. I sent a ping to my Cypriot colleague and she explained that Ancient Greek while primarily written in the Greek Alphabet, does have some tablets written in Cypriot Syllabary, eg. https://en.wikipedia.org/wiki/Idalion_Tablet and the Idalion Bilingual https://crewsproject.wordpress.com/2018/01/28/crews-display-the-idalion-bilingual/

So while we should make sure Grek is the default match for grc -- Crpt was used on occasion. The concern of CLDR is that based on the SIL data, Cprt was the default writing system for Ancient Greek -- it should not be the default, but it is a valid option.

**Comment by DavidLRowe** [comment]
Hmm. IIUC this data in langtags originated with CLDR. We can go ahead and correct it now since the CLDR changes will eventually filter in.

**Pull request closed without merging**
